### ISSUE TITLE
OAuth2 getToken invalid_request

### ISSUE THREAD

**Issue by sejbr** [google/google-auth-library-nodejs#120]
I'm quite new to both NodeJS and the new GoogleApis since I've been always using keys mostly.
I've had quite a stumble with [this](https://developers.google.com/identity/protocols/OAuth2InstalledApp) since it uses different oauth2 urls, be it /oauth2/v2/auth instead of /oauth2/auth and /oauth2/v4/token instead of /oauth2/token, I'm guessing because of the ability not to use secrets for installed apps in those versions.
Any way of changing the versions without editing the privates in oauth2client.js?
I've seen usage like require('googleapis').youtube('v3') but I've tried different things and can't seem to get it to work without changing the consts.

**Comment by JustinBeckwith** [comment]
These urls are changed in #215, which will be in the upcoming 1.0 release of the library.
