### ISSUE TITLE
NodeJs support for verifying Firebase token

### ISSUE THREAD

**Issue by wuyanna** [google/google-auth-library-nodejs#123]
Google python auth library has a method [verify_firebase_token](http://google-auth.readthedocs.io/en/latest/_modules/google/oauth2/id_token.html#verify_firebase_token), to make it much easier for python users to integrate with Firebase Auth. It is important that Nodejs library also has this method for Nodejs users

**Comment by JustinBeckwith** [comment]
There's a great implementation for Firebase and node.js over here:
https://github.com/firebase/firebase-admin-node

Unless there's a really good reason to have it here, I'd rather let the firebase stuff sit over there.  
 Does that npm module work?  If not, let me know, and we can re-open this and take a look  😎
