### ISSUE TITLE
How to check user has authorized to (GSuite Domain-Wide Delegation of Authority) to my application using nodejs

### ISSUE THREAD

**Issue by khatekar** [google/google-auth-library-nodejs#124]
Hello,

Is there any example that I validate the authority of the service account using nodejs?
I have Client ID, client secret Json file and Email address and Scope are https://www.googleapis.com/auth/admin.reports.audit.readonly. 
Its domain wide not a user wide.
I need a nodejs example, which will check if the customer delegate / authorize domain-wide authority to my application. I don't want the user to go to consent UI and grant access to my application. In my case the user (domain administrator) has done all the steps (grant third-party applications with domain-wide access) manually, and I need to see if he correctly grants the access to my application.

Thank you in advance.

**Comment by khatekar** [comment]
I got it working.

Thank you.

**Comment by ybenita123** [comment]
I have the same problem. Can you send me an example?

**Comment by lassmann** [comment]
and the answer is? @khatekar
