### ISSUE TITLE
Allow custom claims in JWTAccess `payload`

### ISSUE THREAD

**Issue by tariqajyusuf** [google/google-auth-library-nodejs#134]
[Google Cloud IAP](https://cloud.google.com/iap) provides the ability to use bearer tokens as a means of authentication. However, a separate claim needs to be provided (`target_audience`) to do this. The current code in lib/auth/jwtaccess.js can do this but needs support for custom claims.

**Comment by lukesneeringer** [comment]
Hi @tariqajyusuf,
Can you help us understand a bit better what it is that you want here? Is this a new feature request? What exactly needs to happen to support your use case?
