### ISSUE TITLE
Obtain dummy or test users id_token

### ISSUE THREAD

**Issue by hmontes** [google/google-auth-library-nodejs#136]
Hi

I'm trying to implement this in my back server (node.js) but i don't have the front part yet.

How can i obtain the id_token? I want to buld the server and test.

Thanks

**Comment by lukesneeringer** [comment]
Hi @hmontes,
Sorry that it took us so long to get back to you. Unfortunately, without more information on what exactly you are trying to do, we probably are not able to help. Please feel free to open a new issue with more details. :-)
