### ISSUE TITLE
Extend getToken to accept a code_verifier

### ISSUE THREAD

**Issue by singhshashi** [google/google-auth-library-nodejs#148]
For OAuth for installed apps, when requesting user authorization, the recommendation is to send a code_challenge. See https://developers.google.com/identity/protocols/OAuth2InstalledApp#create-code-challenge

Then when exchanging the authorization code for refresh and access tokens, the code verifier also has to be sent, if it was sent when requesting authorization. See https://developers.google.com/identity/protocols/OAuth2InstalledApp#exchange-authorization-code

I tried using this OAuth client from google-api-nodejs-client, which I see uses this library. Since the [current getToken method](https://github.com/google/google-auth-library-nodejs/blob/1956db0f24abf7b7eca36638579da1f343300fb7/ts/lib/auth/oauth2client.ts#L124) 

```
public getToken(code: string, opt_callback) {
    const uri = this._opts.tokenUrl || OAuth2Client.GOOGLE_OAUTH2_TOKEN_URL_;
    const values = {
      code: code,
      client_id: this._clientId,
      client_secret: this._clientSecret,
      redirect_uri: this._redirectUri,
      grant_type: 'authorization_code'
    };

    this.transporter.request(
        {method: 'POST', uri: uri, form: values, json: true},
        (err, tokens, response) => {
          if (!err && tokens && tokens.expires_in) {
            tokens.expiry_date =
                ((new Date()).getTime() + (tokens.expires_in * 1000));
            delete tokens.expires_in;
          }
          const done = opt_callback || noop;
          done(err, tokens, response);
        });
  }
```

 does not allow one to pass the code_verifier, the api call was failing with the error 'invalid_grant'  

So I stopped following the recommended approach in the first step of using a code_verifier. 

If the getToken method would support an optional code_verifier parameter, api calls would not fail and the recommeded approach of using a code_verifier could be followed. 

If you agree with this, I can create a pull request with the required changes.

**Comment by JustinBeckwith** [comment]
Fixed in #218
