### ISSUE TITLE
Use gcloud config-helper to read project ID instead of using gcloud config list

### ISSUE THREAD

**Issue by jonparrott** [google/google-auth-library-nodejs#156]
`gcloud config-helper` is designed specifically for the use case of external tools to obtain gcloud's configuration data.

Context: https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/146

**Comment by lukesneeringer** [comment]
But make sure it does not crash in the browser. :-)

**Comment by jmdobry** [comment]
I don't think this library supports the browser.

**Comment by ofrobots** [comment]
Apart from the use of `child_process` (which we can guard), I think it should not be difficult to support this in the browser.

**Comment by JustinBeckwith** [comment]
This will go out with the 1.0 release
