### ISSUE TITLE
No TypeDefinitions in the latest release on NPM

### ISSUE THREAD

**Issue by markpeterfejes** [google/google-auth-library-nodejs#158]
Hey Guys!

Wonderful package you made here! 
Could you please publish a release where you include the TypeDefinition files in the package?

Thank you very much!

**Comment by ofrobots** [comment]
Thanks for opening the issue. We'll try to get a release done next week.

**Comment by Gustav0ar** [comment]
Any news on this? I really need it for my TS Nodejs project

**Comment by markpeterfejes** [comment]
@ofrobots Is there a possibility of a release this week? :)

**Comment by rajshrimohanks** [comment]
Seriously guys, this is a bummer! This is the only thing preventing me from using `"noImplicitAny":true` in my project. :confounded:

**Comment by ofrobots** [comment]
Hi Folks, sorry for the delay. This is the first release we are going to after the conversion to TypeScript. We want to make sure there are no un-intentional semver major changes as a result. There is a little more testing of dependent modules we need to do before we can publish.

**Comment by ofrobots** [comment]
A pre-release version (`0.11.0-0`, tag `next`) is available from npm that includes type definitions. Please give it a try and let us know if there is any feedback.
```
npm install google-auth-library@next
```

**Comment by ofrobots** [comment]
Released as v0.11.0. [Release Notes](https://github.com/google/google-auth-library-nodejs/releases/tag/v0.11.0).
