### ISSUE TITLE
Getting 403s when running as tests in headless Chrome.

### ISSUE THREAD

**Issue by hdavidzhu** [google/google-auth-library-nodejs#165]
```
code: 403,
  errors:
   [ { message: 'The caller does not have permission',
       domain: 'global',
       reason: 'forbidden' } ] }
```

This fails the whole test suite.

**Comment by lukesneeringer** [comment]
@hdavidzhu Do you have reproduction steps?

**Comment by bantini** [comment]
Thank you for filing this issue. We asked some clarifying questions and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
