### ISSUE TITLE
Replace request with http.

### ISSUE THREAD

**Issue by lukesneeringer** [google/google-auth-library-nodejs#166]
We want to replace `request` with `http`.
A pass at this was done in #122, but is no longer valid because we let it drift too far out of date.

This issue exists to track this work.

**Comment by jmdobry** [comment]
Note, if we want to add support for the browser, then we should look at using something like [axios](https://github.com/mzabriskie/axios) as our transport layer.

**Comment by ofrobots** [comment]
I am not that familiar with how people use a node library in the browser, but my understanding is that http module is already supported by browserify. Would that not work?

It is a 'nice to have' thought to be able to work in a browser environment, but if it requires weird contortions for this library to get there then perhaps we should re-think.

BTW, another alternative to using raw http would be to use https://github.com/mikeal/r2 which, being built around `fetch` supports both node and the browser. It is pretty minimal too. One thing @matthewloring  didn't like about it were [these custom promise properties](https://github.com/mikeal/r2/blob/8b07ee30fbb140d2db0db6f2f237b42234ec21a0/index.js#L32) that are probably not best for performance (not that is a pressing concern in this library).

**Comment by JustinBeckwith** [comment]
I have the first cut of this over in #182.  Still working on a few tests and cleanup. Thoughts welcomed!

**Comment by JustinBeckwith** [comment]
This is fixed in the next branch.  As soon as the 1.0 release is ready it will go out.
