### ISSUE TITLE
Expose a `getCredentials` method

### ISSUE THREAD

**Issue by stephenplusplus** [google/google-auth-library-nodejs#169]
The `private_key` and `client_email` properties of a service account JSON file are required for crypto operations, such as generating a signed URL. Example from `@google-cloud/storage`: https://github.com/googleapis/nodejs-storage/blob/469530c744c42096e46f39f409272cca05eaf02a/src/file.js#L1646.

[Evidently](https://github.com/googleapis/nodejs-storage/issues/39), the GCP metadata server can return these values. `google-auth-library` is the most knowledgeable of the environment and authentication choices made by the user, and ideally would expose a method like `authClient.getCredentials()`.

This method would return the contents of the service account JSON key file, or if the user did not give a key file, i.e. they're on GCP, it would read the properties from the metadata server.

**Comment by inlined** [comment]
Just to make sure we're all on the same page, the Google metadata service will not reveal a private key, but that's not needed for the signed URLs in `@google-cloud/storage`. Instead, `@google-cloud/storage` should use an OAuth token from the metadata server and call IAM's `signBlob` API.

**Comment by bantini** [comment]
@stephenplusplus Are there any specific entries that you want from this method or do you want the entire content of the JSON file? 

The format of a service account JSON is as follows:
  
```
{
  "type": "service_account",
  "project_id": "project-id",
  "private_key_id": "private-key-id",
  "private_key": "-----BEGIN PRIVATE KEY-----\nsomeprivatekey\n-----END PRIVATE KEY-----\n",
  "client_email": "client_email@developer.gserviceaccount.com",
  "client_id": "000000000000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/000000000-compute%40developer.gserviceaccount.com"
}
```

**Comment by bantini** [comment]
@lukesneeringer @stephenplusplus What should be the signature of the method? Should it accept a callback to process the data returned by the metadata server/JSON key file or should it return the data directly?

**Comment by lukesneeringer** [comment]
/cc @stephenplusplus for a decision

My gut is that it optionally takes a key file, and it returns a (potentially partial) service account dictionary.

**Comment by stephenplusplus** [comment]
We actually talked it through a bit in the PR: https://github.com/google/google-auth-library-nodejs/pull/180
