### ISSUE TITLE
Node Security Advisory for dependency

### ISSUE THREAD

**Issue by davidpaulhunt** [google/google-auth-library-nodejs#174]
`gtoken` `1.2.3` upgrades a dependency affected by this Node Security Advisory for `mime`: https://nodesecurity.io/advisories/535

Would it be possible to upgrade `gtoken` to `1.2.3`?

**Comment by ofrobots** [comment]
Yes, we can change the semver range to `^1.2.3`, but note that we currently specify `^1.2.1`, so you should already be getting the patched version. IOW, this doesn't seem urgent to require a new release on npm. Here's the [snyk page](https://snyk.io/test/github/google/google-auth-library-nodejs) for this module. Let us know if you disagree.

**Comment by ofrobots** [comment]
#175

**Comment by davidpaulhunt** [comment]
@ofrobots ah, that didn't occur to me! Color me embarrassed, but thanks for changing the semver range and I'll make sure I'm getting the patched version.

Cheers!

**Comment by davidpaulhunt** [comment]
@ofrobots ah, that didn't occur to me! Color me embarrassed, but thanks for changing the semver range and I'll make sure I'm getting the patched version.

Cheers!
