### ISSUE TITLE
Error with typescript: resolves to a non-module entity and cannot be imported using this construct

### ISSUE THREAD

**Issue by dauledk** [google/google-auth-library-nodejs#177]
When I try to use this library with typescript

    import * as googleAuth from 'google-auth-library';

I get the following error: 

    [ts] Module '"<fullpath>/node_modules/google-auth-library/types/lib/index"' resolves to a non-module entity and cannot be imported using this construct.

I am running typescript 2.6.1 and my tsconfig.json look like this: 
  
    {
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es6",
        "lib": [
            "es2017",
            "dom"
        ],
        "module": "commonjs",
        "watch": true,
        // "moduleResolution": "node",
        "sourceMap": true
    },
    "include": [
        "src/**/*",
        "test/**/*",
        "config/**/*"
    ],
    "exclude": [
        "node_modules",
        "typings"
    ]}

**Comment by mrene** [comment]
Import it using that syntax since it's exported as `export = GoogleAuth;` which doesn't make it importable as a module.

 ```typescript
import GoogleAuth from 'google-auth-library'
```

**Comment by dauledk** [comment]
When I use the your suggested import:

    import GoogleAuth from 'google-auth-library';

I get a new error: 

    [ts] Module '"/Users/alexbjorlig/Documents/jernbanecafeen/mailservice2/node_modules/google-auth-library/types/lib/index"' has no default export.

**Comment by ofrobots** [comment]
It seems that `` is working for babel users but not from typescript users.

```js
// index.js
import GoogleAuth from 'google-auth-library';
console.dir(GoogleAuth);
```

```sh
$ npm run build && node lib/index.js

> babel@1.0.0 build /Users/ofrobots/tmp/babel
> babel src -d lib

src/index.js -> lib/index.js
{ [Function: GoogleAuth]
  DefaultTransporter: { [Function: DefaultTransporter] USER_AGENT: 'google-api-nodejs-client/0.11.0' } }
```

```ts
// index.ts
import GoogleAuth from 'google-auth-library';
console.dir(GoogleAuth);
```

```sh
> tsc -p .

src/index.ts(1,8): error TS1192: Module '"/Users/ofrobots/tmp/babel/node_modules/google-auth-library/types/lib/index"' has no default export.
```

This difference needs to be investigated.

**Comment by jinwoo** [comment]
@dauledk Have you tried this?

```typescript
import GoogleAuth = require('google-auth-library');
```

**Comment by dauledk** [comment]
@jinwoo that syntax seems to work. 

Do you mind sharing why this works, I am still relatively new to typescript.

However I still get a ton of compile errors when building. A lot of them comes from the google-auth-library. Like this one 

    <full-path-to-project>/node_modules/google-auth-library/types/lib/transporters.d.ts(1,23): error TS2688: Cannot find type definition file for 'request'.`

So closs to have my small project up and running :)

**Comment by jinwoo** [comment]
@dauledk AFAIK that's the only syntax that works for `export = Foo` style packages.

`import {GoogleAuth} from 'google-auth-library';` works only when `GoogleAuth` is the *default export*.


Going forward, I think we should move away from that and use more ES-module-friendly or TS-friendly export.

**Comment by ofrobots** [comment]
@dauledk I have split the compile error issues into a separate bug #178. In the meanwhile you can workaround it by adding a dev dependency on `@types/request` from your own module: `npm install --save-dev @types/request`.

**Comment by dauledk** [comment]
@ofrobots thanks for the suggestion. 
I ran the command `npm install --save-dev @types/request`, and it helped. However the next errors are of this type: 

```javascript
<full-path-to-project>/node_modules/base64url/typings/globals/node/index.d.ts(2299,14): error TS2300: Duplicate identifier 'internal'.
```

So I tried running `npm i @types --save-dev @types/request` - but it did not help. Do you now any seeed project in typescript using this module? And thanks for the help so far.

**Comment by JustinBeckwith** [comment]
This is fixed in the `next` branch, and will be part of the upcoming 1.0 release.
