### ISSUE TITLE
AuthClient.setCredentials method removed in TypeScript conversion

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-nodejs#189]
A user reported getting an error when upgrading to v23 of the googleapis npm module.  I tracked it down to the TypeScript conversion, where it looks like I accidentally removed the function

https://github.com/google/google-auth-library-nodejs/commit/5735a351269363320288ae9a43dc88937d83323a

We should probably add that back :)

**Comment by JustinBeckwith** [comment]
This was fixed in the `next` branch, and will be part of the 1.0 milestone release.

**Comment by amrsh** [comment]
So...this seems to mean that there is no way to call APIs on behalf of logged in users. Isn't this pretty much half the use cases for this library? Seems like it might warrant a 0.x release to fix, no?

**Comment by JustinBeckwith** [comment]
You can work around this today with 0.x by directly assigning to the credentials property:

`client.credentials = credentials;`

Hope this helps!
