### ISSUE TITLE
Cut the 1.0 release

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-nodejs#197]
After the items in the 1.0 milestone are done, we'll need to cut a release.  Will start by drafting the release with breaking changes and release notes.

**Comment by JustinBeckwith** [comment]
@ofrobots @lukesneeringer @alexander-fenster please let me know if there are any specific issues or bugs you want to see addressed in the 1.0 release here.

**Comment by ofrobots** [comment]
@JustinBeckwith I added some bugs to the 1.0 milestone. All but one might be easy to dispatch.

**Comment by JustinBeckwith** [comment]
@ofrobots I took a first stab at the release notes here:
https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-e411ba680eac6429025c#

Mind taking a look?

**Comment by JustinBeckwith** [comment]
@ofrobots I am struggling to rebase next into master.  If I try running `git rebase upstream/next` while in the master branch, it tells me that we've diverged by 3 commits.  If I try to `git rebase upstream/master` while in the next branch, the results are just... plain wrong.  

What's the right way to get the changes from the `next` branch into `master`!?

**Comment by ofrobots** [comment]
I did the rebase and then force pushed the `next` branch. CI is here: https://travis-ci.org/google/google-auth-library-nodejs/builds/326617053

**Comment by JustinBeckwith** [comment]
Ok, I'm ready to cut the release.  Any objections?

**Comment by JustinBeckwith** [comment]
And 1.0 is out :)
