### ISSUE TITLE
Smoke test against downstream dependents in prep for 1.0 release

### ISSUE THREAD

**Issue by ofrobots** [google/google-auth-library-nodejs#205]
The 1.0 release is going to have breaking changes. Let's smoke test / integration against some hand-selected downstream dependent modules to make sure there aren't any surprises.

A pre-release `1.0.0-alpha.1` is available from npm under the `next` tag. Also see the [release notes](https://github.com/google/google-auth-library-nodejs/releases/tag/1.0.0-alpha.1).

- [x] [firebase-admin](https://www.npmjs.com/package/firebase-admin). @ofrobots PR: https://github.com/firebase/firebase-admin-node/pull/152
- [x] [googleapis](https://www.npmjs.com/package/googleapis). @JustinBeckwith https://github.com/google/google-api-nodejs-client/pull/891
- [x] [actions-on-google](https://www.npmjs.com/package/actions-on-google) @ofrobots PR: https://github.com/actions-on-google/actions-on-google-nodejs/pull/78
- [ ] Veneer libraries and [google-auto-auth](https://www.npmjs.com/package/google-auto-auth) @stephenplusplus @alexander-fenster
~~- [ ] Samples: https://github.com/GoogleCloudPlatform/nodejs-docs-samples~~ (this doesn't directly use the `google-auth-library` anywhere.  It lists it as a dependency once, but doesn't actually use it 

Feel free to add more to the list. For reference, see [the full list of dependent modules](https://www.npmjs.com/browse/depended/google-auth-library).

**Comment by stephenplusplus** [comment]
I'm assuming this question will have a quick, logical answer, so I'll just pop it in here to confirm instead of a new issue.

```js
var GoogleAuth = require('google-auth-library').GoogleAuth;
```

Why not just:

```js
var GoogleAuth = require('google-auth-library');
```

?

**Comment by JustinBeckwith** [comment]
Good question!  It's largely an issue of a.) wanting to be es6 module compatible, and b.) the Google TypeScript style guide not allowing default exports.

I'm personally open to the default export, and kind of think it would be a nicer experience.  @ofrobots what are your thoughts here?

**Comment by JustinBeckwith** [comment]
@ofrobots how are you feeling here?  Think we need to dig deeper, or are we pretty close to a release?

**Comment by ofrobots** [comment]
Sorry for missing the pings earlier.

> var GoogleAuth = require('google-auth-library').GoogleAuth;

I would argue that the default/common usage of the module is going to look like this:

```js
const {GoogleAuth} = require('google-auth-library');
```

I think this is quite idiomatic and natural. Yes, this doesn't work with Node 4, but that has only 4 months left before it goes EOL.

**Comment by stephenplusplus** [comment]
I'm definitely behind on my modern-JS conventions, but is that really the case? I'll be looking at:

```js
const fs = require('fs')
const request = require('request')
const {GoogleAuth} = require('google-auth-library')
```

**Comment by ofrobots** [comment]
IMO, modern JS is indeed headed this way. Let's look at Node.js core itself: https://github.com/nodejs/node/blob/1d8789188fa156d5eb75c155f6c648c2bd96b842/lib/child_process.js#L24-L39

When ESM rolls around, this will naturally lead to idiomatic code regardless of how CJS and ESM interop is going to work (still being worked on). It is not a given that a default-style CJS export will interoperate when ESM ship.

The TypeScript style guide bans default exports because that leads to a consistent import syntax. If we are going to disagree with the style guide, let's take that up as a bug against the style guide be prepared to make the case for it. This is not the venue.

Making individual exceptions in different modules is going to lead to inconsistent import syntax for each given Google npm module.

**Comment by stephenplusplus** [comment]
That link is good enough. As long as there is precedent, might as well go with it. This won’t be my first “hmm... ok...” on modern JS developments. I’m just happy when everyone knows what to expect and gets it. So if that’s what we’re doing here, SGTM.

**Comment by JustinBeckwith** [comment]
@ofrobots I'm happy with the smoke testing here, and feel generally ready to release.  Let me know what you think we should do to finish this one out :)

**Comment by ofrobots** [comment]
Sounds good to me. Closing as complete.
