### ISSUE TITLE
Reference docs?

### ISSUE THREAD

**Issue by broady** [google/google-auth-library-nodejs#206]
Where are the reference docs? What is the type of "authClient" in the example in the README? How can you use it by itself?

**Comment by JustinBeckwith** [comment]
As it would turn out, this is annoyingly hard with TypeScript.  I tried a few methods:
- **Using [esdoc](https://github.com/esdoc/esdoc), with the [TypeScript plugin](https://github.com/esdoc/esdoc-plugins/tree/master/esdoc-typescript-plugin).**  - This was really just a glorified jsdoc comment parser.  The TypeScript doesn't appear to actually read types from the TypeScript code, and produces low quality typing information.
- **Using [TypeDoc](https://github.com/TypeStrong/typedoc).** - TypeDoc doesn't appear to be maintained very well, and crashes with TypeScript 2.6.  I was able to [hack up a fix](https://github.com/JustinBeckwith/typedoc/commit/f37fff4dca14f05ae90fa7cfef30a6df98b1b208), but it doesn't appear as though they're handling pull requests in a timely manner.  

Right now, TypeDoc seems like the best bet.  I have the preview docs published here:
https://auth-library.firebaseapp.com/

The docs are showing each class as a global entity, which is wrong.  I need to figure out how to bend TypeDoc to use a module entry point (index) as the jumping point.  I'll keep banging on this until it's reasonably good.

In the interim - we've really expanded the examples section in the `next` branch.

**Comment by JustinBeckwith** [comment]
Another alternative here is to just add duplicate jsdoc annotations to the TypeScript classes and properties, purely for the purposes of generating decent documentation.  Thoughts @ofrobots?

**Comment by ofrobots** [comment]
Code that is not never tested/compiled by a compiler is worse than no code at all. IMO jsdoc type annotations fall into this category and would be fast out of date and worse than no docs.

deeplearn.js seems to have some pretty reasonable docs generated using typedoc: https://deeplearnjs.org/docs/api/globals.html. Perhaps we can follow their setup?

**Comment by JustinBeckwith** [comment]
Fixed in #237
