### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by zoellner** [google/google-auth-library-nodejs#234]
Changelog is outdated. last documented change is from 12/29/2016
However there are changes in this library that introduce breaking changes in google/google-api-nodejs-client. see google/google-api-nodejs-client#894

**Comment by JustinBeckwith** [comment]
Apologies.  This was an oversight, and was addressed in #198.  It will be part of the 1.0 release, and you can track that over in #197.

**Comment by JustinBeckwith** [comment]
This was fixed in the 1.0 release, and is now updated in https://github.com/google/google-api-nodejs-client/pull/891

**Comment by nopnop** [comment]
Hi @JustinBeckwith, maybe @zoellner issue was related to this file https://github.com/google/google-auth-library-nodejs/blob/master/CHANGELOG.md which is still outdated.
It is a bit confusing at first, found this issue, then ... I eventually scrolled the README.md

**Comment by zoellner** [comment]
that's correct. the CHANGELOG.md file is what I stumbled across when I was debugging that issue.

**Comment by JustinBeckwith** [comment]
Ah, that makes a lot more sense :)  That's an easy change.  Will submit a PR soon!

**Comment by JustinBeckwith** [comment]
The change log has now been entirely moved to GitHub release notes, and it includes these changes :) Thanks folks!
