### ISSUE TITLE
0.9.4 Causes error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by alexmuro** [google/google-auth-library-nodejs#24]
Full error is 
139661365319552:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:696:Expecting: ANY PRIVATE KEY

I use google apis node for big query in some of my projects and was wiping my node_modules for anther reason. When I restart my project I got the above error even though my pem key hadn't changed. I got a new pem key but that didn't change the error.

 After some investigation I found that the google-auth-library had bumped from 0.9.3 to 0.9.4. Forcing it back to 0.9.3 with my original pem key auths fixed the problem.

**Comment by ryanseys** [comment]
How are you creating the `pem` key file given the `p12` file?

**Comment by ryanseys** [comment]
Try using the `p12` (which is supported in `0.9.4`) file directly and see if that works. I believe the issue may be that the PEM file includes certificates. You can try to generate the `pem` from the `p12` using the command found here: https://github.com/ryanseys/node-gtoken#converting-your-p12-key-to-a-pem-key

This might be an issue that needs to be addressed in the node-gtoken library referenced in the link above.

**Comment by alexmuro** [comment]
I used 
openssl pkcs12 -in key.p12 -out key.pem -nodes -nocerts

to create the pem which is slightly different from what is linked, but I think works the same. I will try to generate a new key with 

openssl pkcs12 -in key.p12 -nodes -nocerts > key.pem

 and see if that works.

Will also try to p12.

I don't have the p12 for my original pem key so will have to try just for the new one.

**Comment by JustinBeckwith** [comment]
Using the 1.0 release in the `next` branch, I was able to get this working with both the p12 file and the pem file generated from your command:

```js

const {JWT} = require('../build/src/index');

/**
 * The JWT authorization is ideal for performing server-to-server
 * communication without asking for user consent.
 *
 * Suggested reading for Admin SDK users using service accounts:
 * https://developers.google.com/admin-sdk/directory/v1/guides/delegation
 **/

async function main() {
  const client = new JWT(
    'theemail',
    './cloudcats-next.pem',
    null,
    'https://www.googleapis.com/auth/cloud-platform'
  );
  await client.authorize();
  const url = `https://www.googleapis.com/dns/v1/projects/cloudcats-next`;
  const res = await client.request({ url });
  console.log(res.data);
}

main().catch(console.error);
```

Looks like this is all cleared up :)
