### ISSUE TITLE
what is the latest version?

### ISSUE THREAD

**Issue by rabashani** [google/google-auth-library-nodejs#241]
for some reason, `npm install google-auth-library` set the version to 0.12.0 while it appears that there is another version called 1.0

![image](https://user-images.githubusercontent.com/202980/34718338-ecbaee9c-f53e-11e7-938f-658ae6e1acfc.png)

**Comment by JustinBeckwith** [comment]
Greetings!  Apologies for any confusion.  
- The current latest stable release is 0.12.  
- There is a preview of the 1.0 release available [here](https://github.com/google/google-auth-library-nodejs/releases/tag/1.0.0-alpha.1)
- We just merged our 1.0 branch into master, and expect to have a 1.0 release today.
