### ISSUE TITLE
Get an error when I try to run 'Using JSON Web Tokens' example

### ISSUE THREAD

**Issue by mmhiguera** [google/google-auth-library-nodejs#244]
TypeError: JWT is not a constructor, and why use `const {JWT} = require('../build/src/index');` instead of `const {JWT} = require('google-auth-library');`

**Comment by JustinBeckwith** [comment]
Yeah, for all of the samples today you need to replace the import in the way you described.  I went ahead and submitted #245 to make this easier :)

**Comment by JustinBeckwith** [comment]
Fixed in #245

**Comment by mmhiguera** [comment]
Yes, I did it but I still get the same error 

> is not a constructor
 
this time I am trying to use GoogleAuth

**Comment by JustinBeckwith** [comment]
Apologies for the issues.  Can you share:
- The complete code sample you're trying to use
- The version of node.js you're running
- Your package.json

Thanks!
