### ISSUE TITLE
Broken samples/jwt.js link in README

### ISSUE THREAD

**Issue by njseeto** [google/google-auth-library-nodejs#252]
Hi 👋 
I've found a broken link in the README, samples/jwt.js - I _think_ it might be examples/jwt.js ? Although that file does not mention `.pem` so this could also be incorrect.
Contributing to open source is new to me so am happy to make a PR if this is the correct link.
Thanks!

**Comment by JustinBeckwith** [comment]
Great catch!  You're completely right.  We would love a PR to fix this :)

**Comment by njseeto** [comment]
Changes have been added  🙌

**Comment by JustinBeckwith** [comment]
Addressed in #253 - Thanks again!
