### ISSUE TITLE
Illegal Access

### ISSUE THREAD

**Issue by jonstorer** [google/google-auth-library-nodejs#27]
Throws "illegal access" when `toString` is called on the error created in [lib/transporters.js#78](https://github.com/google/google-auth-library-nodejs/blob/master/lib/transporters.js#L78). The error is not thrown if line [#80](https://github.com/google/google-auth-library-nodejs/blob/master/lib/transporters.js#L80) is removed.

- http://www.karadzhov.com/2014/06/nodejs-and-illegal-access-error.html
- https://code.google.com/p/v8/issues/detail?id=2397

node -v 0.10.26
npm -v 1.4.3

(will upgrade node/npm as soon as I'm stable.)

**Comment by prashanthsadasivan** [comment]
+1

**Comment by oscarjgarza** [comment]
+1

**Comment by nateschulte** [comment]
+1

**Comment by tbetbetbe** [comment]
FYI: this is being addressed in #21

**Comment by tbetbetbe** [comment]
Fixed by #21
