### ISSUE TITLE
Using application default auth login throwing Missing Metadata-Flavor:Google

### ISSUE THREAD

**Issue by popkutty** [google/google-auth-library-nodejs#275]
Trying to access iam API with default credentials in cloud instance. Getting `Missing Metadata-Flavor:Google` error when I execute the call. Same working fine when I use my local dev environment with `gcloud auth application-default login` Changing the following code `google-auth-library/build/src/auth/computeclient.js` 

```
case 1:
        _a.trys.push([1, 3, , 4]);
       return [4 /*yield*/, this.transporter.request({ url: url, headers: {'Metadata-Flavor': 'Google'} })];

``` 

working fine. 

My code to access iam API 

```
var google = require('googleapis');
var iam = google.iam('v1');
const {auth} = require('google-auth-library');


let headerPayload = { name: 'name', auth: '', resource: '' }
let currentTime = Math.floor(new Date() / 1000);
let expiry = currentTime + 1000;

auth.getApplicationDefault().then(function (authRes) {
  let options = { payload: JSON.stringify({
      iat: currentTime,
      exp: expiry,
      iss: '.....iam.gserviceaccount.com',
      sub: '....iam.gserviceaccount.com',
      aud: ',.....',
      email: '.....gserviceaccount.com'
  }) }
  headerPayload.resource = options;
 
  headerPayload.auth = authRes.credential;
  
  iam.projects.serviceAccounts.signJwt(headerPayload, function (err, res) {
    console.log((res));
  });

});
```

Response

```Your client does not have permission to get URL <code>/computeMetadata/v1/instance/service-accounts/default/token</code> from this server. Missing Metadata-Flavor:Google header.```

**Comment by popkutty** [comment]
I have this error after the release of google-auth-library 1.2.0. Fixing the version of this package in my package.json to ~1.1.0 removed the problem for me.

**Comment by popkutty** [comment]
@JustinBeckwith When this will be available for consumption.

**Comment by JustinBeckwith** [comment]
It's already released in 1.2.1 :). Can you verify it's working for you?

**Comment by popkutty** [comment]
Will do. I'm so proud of my self, I contributed something to Google 💃

**Comment by JustinBeckwith** [comment]
Thanks for the help!
