### ISSUE TITLE
Update developer.google.com docs

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-nodejs#285]
With the breaking changes in the 1.0 release, it looks like we left some outdated code samples lying around:
https://github.com/google/google-auth-library-nodejs/pull/243#issuecomment-365678552

For example, this has the signature of `verifyIdToken` wrong:
https://developers.google.com/identity/sign-in/web/backend-auth#send-the-id-token-to-your-server

I'm happy to do GitHub stuff, but once it gets into Google3 I'd very much prefer someone else take this on :)

**Comment by JustinBeckwith** [comment]
cc @jonparrott

**Comment by jmdobry** [comment]
If you can send me what the new Node.js sample for https://developers.google.com/identity/sign-in/web/backend-auth#using-a-google-api-client-library should be, I'll update it in the docs.

**Comment by JustinBeckwith** [comment]
From a process perspective - is there a way to get these samples into source control and tested, similar to what you do with cloudsite?  This is going to be a persistent problem otherwise.

**Comment by JustinBeckwith** [comment]
Quick *ping* :) @jonparrott @jmdobry

**Comment by Boboss74** [comment]
Maybe, as a first step, add a warning message about the outdated documentation

**Comment by JustinBeckwith** [comment]
I submitted a PR that I'm waiting for approval on.  I'm closing this one as a dup of #251 since it's about the same doc :)
