### ISSUE TITLE
sample code for `getApplicationDefault` seems wrong 

### ISSUE THREAD

**Issue by phearme** [google/google-auth-library-nodejs#293]
Hi.
In the README the following sample code doesn't seem to work for me:
```javascript
async function getADC() {
  // Acquire a client and the projectId based on the environment. This method looks
  // for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS environment variables.
  const res = await auth.getApplicationDefault();
  let client = res.credential;
```

I think it's rather `res.credentials`? with an `s`?

**Comment by JustinBeckwith** [comment]
The code here should be correct.  We return an object that looks like this:

```ts
export interface ADCResponse {
  credential: OAuth2Client;
  projectId: string|null;
}
```

The variable name `credential` here is unfortunate, because in reality it's a reference to your client.  That "credential" object has a reference to the `credentials` property, which contains your token information:

```ts
export interface Credentials {
  refresh_token?: string|null;
  expiry_date?: number|null;
  access_token?: string|null;
  token_type?: string|null;
  id_token?: string|null;
}
```

If this code isn't working for you - can you share the error you're getting?  Also, 100% of the code in that snippet comes from [examples/adc.js](https://github.com/google/google-auth-library-nodejs/blob/master/examples/adc.js), which I just tested to make sure it works.  Can you give that a spin?

**Comment by phearme** [comment]
@JustinBeckwith thanks for your answer.

node version: v6.13.0
google-auth-library: "^1.2.1"
`GOOGLE_APPLICATION_CREDENTIALS` environment variable pointing to a json token generated from google cloud from a service account.

I'm using vanilla js code:

```javascript
var {auth} = require("google-auth-library");

auth.getApplicationDefault(function (err, res) {
    if (err) { console.log(err); }
    var client = res.credential;
    console.log(client); // => undefined
    console.log(res);
});
```

here is what I get in return of `res` which looks like a json web token:
```
JWT {
  transporter: DefaultTransporter {},
  certificateCache: null,
  certificateExpiry: null,
  _clientId: undefined,
  _clientSecret: undefined,
  redirectUri: undefined,
  authBaseUrl: undefined,
  tokenUrl: undefined,
  credentials: { refresh_token: 'jwt-placeholder', expiry_date: 1 },
  eagerRefreshThresholdMillis: 300000,
  email: '****@appspot.gserviceaccount.com',
  keyFile: undefined,
  key: '-----BEGIN PRIVATE KEY-----\n****\n-----END PRIVATE KEY-----\n',
  scopes: undefined,
  subject: undefined,
  additionalClaims: undefined,
  projectId: '****' }
```

**Comment by JustinBeckwith** [comment]
Yeah, this is just a case of confusing property names.  This works great:

```js
auth.getApplicationDefault(function (err, client) {
    if (err) {
      console.log(err);
    }
    console.log(client);
    console.log(client.credentials);
  });
```

You were looking for `res.credentials`, not `res.credential`.  In the example code you were referring to, `res.credential` refers to an OAuth2Client object, so you would be looking for `res.credential.credentials`.  

Apologies for the confusion!  I opened #298 to make this all more obvious in the API.

**Comment by phearme** [comment]
@JustinBeckwith thanks. indeed very confusing. I suggest that at least in the code example, clearly state which property is populated for which type of expected resulting client.
