### ISSUE TITLE
Migrate transport tests from google-api-nodejs-client

### ISSUE THREAD

**Issue by tbetbetbe** [google/google-auth-library-nodejs#30]
This is a follow-up to #21, which corrects an issue that's currently only tested in google-api-nodejs-client.
Those tests should be moved this repo.

**Comment by JustinBeckwith** [comment]
As far as I can tell, all of the tests that remain in google-api-nodejs-client in test.transporters.ts are specific to the functionality as it pertains to that library.  There's a decent set of tests in the google-auth-library test suite to cover the transporter functionality.  If new issues come up with a lack of test coverage, we can address those as we go.
