### ISSUE TITLE
unable to import library 

### ISSUE THREAD

**Issue by prashantharshi** [google/google-auth-library-nodejs#312]
i am unable to import the library , it fails with the error 
<img width="572" alt="err" src="https://user-images.githubusercontent.com/8679965/37078324-cc871798-2204-11e8-9ab3-22adf30d4ac3.png">
at line : var gtoken_1 = require("gtoken");

node version : v5.10.1
npm version: 5.4.0

**Comment by JustinBeckwith** [comment]
Greetings!  A few thoughts here.

1. This library isn't tested at all on Node.js 5.x.  5.x is an odd numbered major release, which means that support stopped as soon as 6.x went LTS.  You should really upgrade to 6.x, which should be compatible with your 5.x code. 

2. It looks like you're using webpack.  This library is not meant for the browser.  If you're looking for a browser implementation of OAuth2, you should check out the google javascript api client:
https://developers.google.com/api-client-library/javascript/start/start-js

Hope this helps!

**Comment by prashantharshi** [comment]
Thanks justin

yes i am using webpack , Thanks for the direction !
