### ISSUE TITLE
JWT: Can I call `getCredentials`?

### ISSUE THREAD

**Issue by stephenplusplus** [google/google-auth-library-nodejs#313]
The JWTClient doesn't appear to let me call a "getCredentials()" function. Ideally, the JWTClient could recognize the p12/pem file, parse it, and internally store then return the private key from `getCredentials()`.

**Comment by JustinBeckwith** [comment]
Yeah, best I can tell there's no way to do this today in the way you want.  We'd have to modify node-gtoken to offer a method that just parses the keys and returns the metadata.  If it's ok to include the request to get the token, this is a cheap way to do it today :)

```js
const {auth} = require('google-auth-library');
const client = await auth.getClient();
const token = await client.authorize();
console.log(client.key);
```

**Comment by stephenplusplus** [comment]
Thanks for the tip! I did it that way from the google-auto-auth `getCredentials()` function.
