### ISSUE TITLE
Use consistent hostname when referring to metadata service

### ISSUE THREAD

**Issue by drewbryant** [google/google-auth-library-nodejs#32]
Two different hostnames are being used to refer to the metadata service.

metadata.google.internal
https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/googleauth.js#L158

metadata:
https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/computeclient.js#L26

**Comment by tullmann** [comment]
I just ran into this and noticed it has recently been fixed by https://github.com/google/google-auth-library-nodejs/commit/610ab17ad4623373d0bd5df683ddd12f4802bc1c
