### ISSUE TITLE
verifyIdToken not throwing error when wrong client ID is passed

### ISSUE THREAD

**Issue by gregdumb** [google/google-auth-library-nodejs#326]
I'm trying to force my ID token verification to fail by giving it a bogus client ID but it accepts it anyway.
My code:
```js
const { OAuth2Client } = require('google-auth-library');
const audiance = 'foobar'; // Bogus client ID defined
var gapiClient = new OAuth2Client(audiance, '', '');

const parser = (idToken, onSuccess, onFailure) => {
    gapiClient.verifyIdToken({idToken, audiance}) // Bogus client ID is passed into function
    .then(login => {
        onSuccess(login.getPayload()); // This callback gets called!
    })
    .catch(error => {
        if(onFailure) onFailure(error); // Not this one
    });
}

module.exports = parser;
```
From reading the docs and looking at this part of the code:
https://github.com/google/google-auth-library-nodejs/blob/c15cc25addb9981e471627839e87c45c88cf2a77/src/auth/oauth2client.ts#L908-L925
it seems to me that it should be throwing a 'wrong recipient' error.

I can easily manually check the IDs myself but now I'm not sure if I should. Is this behavior intended?

**Comment by JustinBeckwith** [comment]
Greetings!  I just did a quick check over here, and everything appears to be working:
https://github.com/google/google-auth-library-nodejs/blob/master/examples/verifyIdToken.js

What I don't see with your code snippet are the steps to acquire the idToken.  If you're passing a bogus clientId into the OAuth2Client constructor, that should cause a failure when you try to open the OAuth2 consent dialog with an 'invalid client' error.  It should also fail when you try to call `getToken`.  So what I'm missing here is...  how are you getting your idToken?

**Comment by gregdumb** [comment]
The valid ID token is coming from the front end using [this](https://github.com/anthonyjgrove/react-google-login) React wrapper for Google's library (set up with my real client ID). I'm passing that token to the server to my parser function up there, where the OAuth2Client was initialized with 'foobar' as the client ID. Since the OAuth2Client is analyzing the token thinking that 'foobar' is the proper client ID, shouldn't it reject the token that was generated based on my real client ID?

I hope this makes sense :)

**Comment by JustinBeckwith** [comment]
Can you share a complete code sample that shows the behavior?  The code I have below throws an exception with `Error: Wrong recipient, payload audience != requiredAudience`

```js
const { OAuth2Client } = require('google-auth-library');
const http = require('http');
const url = require('url');
const querystring = require('querystring');
const opn = require('opn');
const destroyer = require('server-destroy');

// Download your OAuth2 configuration from the Google
const keys = require('./oauth2.keys.json');

async function main() {
  const oAuth2Client = await getAuthenticatedClient();

  // Verify the id_token, and access the claims.
  const ticket = await oAuth2Client.verifyIdToken({
    idToken: oAuth2Client.credentials.id_token,
    audience: 'not-a-real-client-id' //keys.web.client_id
  });
  console.log(ticket);

  // You can use this info to get user information too.
  const url = `https://www.googleapis.com/plus/v1/people/me`;
  const res = await oAuth2Client.request({ url });
  console.log(res.data);
}

/**
 * Create a new OAuth2Client, and go through the OAuth2 content
 * workflow.  Return the full client to the callback.
 */
function getAuthenticatedClient() {
  return new Promise((resolve, reject) => {
    // create an oAuth client to authorize the API call.  Secrets are kept in a `keys.json` file,
    // which should be downloaded from the Google Developers Console.
    const oAuth2Client = new OAuth2Client(
      keys.web.client_id,
      keys.web.client_secret,
      keys.web.redirect_uris[0]
    );

    // Generate the url that will be used for the consent dialog.
    const authorizeUrl = oAuth2Client.generateAuthUrl({
      scope: [
        'https://www.googleapis.com/auth/plus.login',
        'https://www.googleapis.com/auth/plus.me',
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile',
        'email'
      ]
    });

    // Open an http server to accept the oauth callback. In this simple example, the
    // only request to our webserver is to /oauth2callback?code=<code>
    const server = http
      .createServer(async (req, res) => {
        if (req.url.indexOf('/oauth2callback') > -1) {
          try {
            // acquire the code from the querystring, and close the web server.
            const qs = querystring.parse(url.parse(req.url).query);
            console.log(`Code is ${qs.code}`);
            res.end('Authentication successful! Please return to the console.');
            server.destroy();

            // Now that we have the code, use that to acquire tokens.
            const r = await oAuth2Client.getToken(qs.code);
            // Make sure to set the credentials on the OAuth2 client.
            oAuth2Client.setCredentials(r.tokens);
            console.info('Tokens acquired.');
            resolve(oAuth2Client);
          } catch (e) {
            reject(e);
          }
        }
      })
      .listen(3000, () => {
        // open the browser to the authorize url to start the workflow
        opn(authorizeUrl, {wait: false}).then(cp => cp.unref());
      });
      destroyer(server);
  });
}

main().catch(console.error);
```

**Comment by gregdumb** [comment]
Hold on, in `verifyIdToken({idToken, audiance})`, is this `audience` supposed to be the client ID that the server is looking for and checking against, or the client ID that the client used to generate the token? I am under the impression that both `audience`s, there and in the OAuth2Client constructor, are supposed to be the server's copy of the client ID. Is this wrong? And if I am wrong, does that mean when the client authenticates it needs to send an ID token AND a client ID?

I'll have a complete sample ready soon.

**Comment by green-coder** [comment]
@gregdumb Maybe, double-check that you spelled `audience` correctly in your `verifyIdToken({idToken, audience})` .. that's not `audiance`.

**Comment by gregdumb** [comment]
@green-coder THANK YOU that was it! Looks like I need to learn to spell. @JustinBeckwith thanks for your help as well. It works as expected now.

**Comment by green-coder** [comment]
Yuo'er wleocme !
