### ISSUE TITLE
Bad code excerpt related to `verifyIdToken`

### ISSUE THREAD

**Issue by DomDerrien** [google/google-auth-library-nodejs#330]
I'm not sure that the best place to report such an issue, but I did not find any other means...

In the document of [One-tap sign-up and auto sign-in on websites](https://developers.google.com/identity/one-tap/web/idtoken-auth), the code excerpt on how to verify the token with node.js starts with:

``` js
var GoogleAuth = require('google-auth-library');
var auth = new GoogleAuth;
var client = new auth.OAuth2(CLIENT_ID, '', '');
```

It should be :

``` js
const { OAuth2Client } = require('google-auth-library');
var client = new OAuth2Client(CLIENT_ID, '', '');
```

I got it right thanks to issue #326 by reported by @gregdump.

**Comment by JustinBeckwith** [comment]
Thanks for the heads up!  I've submitted a fix, and it should be rolled out soon 👍

**Comment by JustinBeckwith** [comment]
New docs are pushed!
