### ISSUE TITLE
Error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential

### ISSUE THREAD

**Issue by stephenplusplus** [google/google-auth-library-nodejs#334]
###### Copied from original issue: https://github.com/googleapis/nodejs-spanner/issues/143

<a href="/hugoluchessi"><img src="https://avatars2.githubusercontent.com/u/16761951?s=88&v=4" height=44 width=44 align=left></a>@hugoluchessi<br>March 6, 2018 5:52 PM

Hi, this errors has being occurring intermittently on my Cloud Function using Spanner.

The thing is that this error never occured until yesterday (march 5th, 4:09PM -3:00).

Could you please help me to workaround this issue?

#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: -
  - npm version: -
  - @google-cloud/spanner version:  ^1.0.2

#### Steps to reproduce
Not deterministic

**Comment by stephenplusplus** [comment]
<a href="/hugoluchessi"><img src="https://avatars2.githubusercontent.com/u/16761951?s=88&v=4" height=44 width=44 align=left></a>@hugoluchessi<br>March 6, 2018 6:04 PM

I've jsut updated spanner client version to "^1.1.0" to check if it solves the issue.

But as no new releases has been released yesterday regarding spanner or auth, I'm skeptic this will work.

**Comment by stephenplusplus** [comment]
###### _March 6, 2018 6:18 PM_

Interesting. We did recently upgrade the auth layer, [`google-auth-library`](https://gitnpm.com/google-auth-library).

Tagging a related issue: https://github.com/google/google-auth-library-nodejs/issues/168

What version were you using before, when the error started?

**Comment by stephenplusplus** [comment]
<a href="/hugoluchessi"><img src="https://avatars2.githubusercontent.com/u/16761951?s=88&v=4" height=44 width=44 align=left></a>@hugoluchessi<br>March 6, 2018 6:28 PM

I was using ^1.0.2 for some weeks already and no errors of this kind were noticed before yesterday.

I didn't change any code yesterday, I have just updated the versions (30 minutes ago).

**Comment by stephenplusplus** [comment]
###### _March 7, 2018 10:21 PM_

This is going to be a hard one to attempt to reproduce. Could you work up any more details about the calls you're making that might lead to this error? If we're still stuck with only this error to go by, I'll move this over to the auth repo, to see if that team can come up with anything.

One thing that might help, if you're not already doing it. Instantiate the Spanner client inside of the exported GCF function, itself, i.e.

```diff
const Spanner = require('@google-cloud/spanner')
- const spanner = new Spanner()

module.exports.fn = () => {
+ const spanner = new Spanner()
}
```

**Comment by stephenplusplus** [comment]
###### _March 19, 2018 3:13 PM_

Hey @hugoluchessi, just wanted to check in for any updates you might have before I move this over.

**Comment by JustinBeckwith** [comment]
This looks like a request that just doesn't have an authorization header associated with it.  A code sample that reproduces the issue would be very helpful :)

**Comment by JustinBeckwith** [comment]
Greetings folks! In the absence of more information, there's not a lot I can do here.  If someone can provide a consistent repo, I'd be happy to take a look :)

**Comment by wuhduhren** [comment]
For the one who requires BigQuery Client in Cloud Function:
Cloud function caches global variable when they cold start the function.
When cloud function get request continually for an hour, the access token you acquired by your credential expired. 
If you solve this by putting `const bigquery = new BigQuery()` within the function, your function will be super slow since it has to acquired access token all over again every time it gets called.
A simple work around is to add a global variable to track the time update.
`
let timeUpdate = 0; // if bigquery get cached timeUpdate will also get cached
let bigquery = new BigQuery({
    projectId: 'xxxxx',
    keyFilename: 'xxxxx.json'
});

exports.yourcloudfunction = (req, res) => {
    const timeNow = Math.floor(new Date().getTime()/1000);
    ...
    ...

    // before you call bigquery
    // update access token every 45min
    if (timeNow-timeUpdate>2700) {
        bigquery = new BigQuery({
            projectId: 'xxxxx',
            keyFilename: 'xxxxx.json'
        });
        timeUpdate = timeNow;
    }

...

};
`
