### ISSUE TITLE
How to set token expiry or query token expiry when using google.auth.JWT

### ISSUE THREAD

**Issue by MichaelBurgess** [google/google-auth-library-nodejs#335]
Hi,

When we use this JWT client, I cannot see any way to set the expiry for the token, or if there isn't a way to set the expiry, how we can query the token to find its expiry?

I have read somewhere that the expiry defaults to 1hr, but if there is any way for this to vary I'd like to be able to either control or query this so we know how long we can cache the generated token for.

I can't see any mention of this in the samples or docs and looking at the code I can't see any mechanism to control it, so thought best to check directly?

Many thanks,
Mike.

**Comment by JustinBeckwith** [comment]
Greetings!  In general, the library will automatically manage the expiration of the JWT token.  It will grab the expiration time, and with each request auto-refresh if needed. 

If you want to see the expiration date - you can check out `client.credentials.expiry_date` after calling `authorize` or `request` on the client object.  

For example:

```js
const keys = require('./jwt.keys.json');

async function main() {
  const client = new JWT({
    email: keys.client_email,
    key: keys.private_key,
    scopes: ['https://www.googleapis.com/auth/cloud-platform']
  });
  await client.authorize();
  console.log(client.credentials.expiry_date);
  // const url = `https://www.googleapis.com/dns/v1/projects/${keys.project_id}`;
  // const res = await client.request({ url });
  // console.log(res.data);
}

main().catch(console.error);
```

Hope this helps!

**Comment by Burnett2k** [comment]
For the auto-refresh of the tokens to work, do you have to actually use the client to make the requests or can you use something like axios? I'm working on making sure we aren't constantly making network calls every time to retrieve a token, but I cannot find any good examples of how to handle expirations.
