### ISSUE TITLE
Cache promise for refreshToken requests

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-nodejs#338]
We're getting reports of 1000s of connections to googleapis when a flood of new requests come in with an expired access token.  We should cache a single promise for refreshToken requests, and return that when the refresh is in transit.

**Comment by idofl** [comment]
Hi,
I used Firestore with 1000 set of new documents, and got 1000 new TLS connections open to https://www.googleapis.com. Can't verify it's indeed auth, but Firestore and gRPC people say it's probably the auth part, as the Firestore APIs are firestore.googleapis.com (and for that I only get one connection). This was the code:
var admin = require('firebase-admin');
const uuidv4 = require('uuid/v4');

admin.initializeApp({
  projectId: "some project id",
  keyFilename: 'service account credentials.json'
});

var db = admin.firestore();
var collRef = db.collection('test')
var counter = 0;
var iterations = 1000;
for (var i = 1; i <= iterations; i++) {
    var docAndFirstName = uuidv4();
    var setAda = collRef.doc(docAndFirstName).set({
        first: docAndFirstName,
        last: 'Ros',
        born: 1814
    }).then(
        result => {
            counter++;
            if (counter == 1 || counter == iterations)
                console.log(result.writeTime);                             
        }
    );
}

**Comment by idofl** [comment]
Hi Justin,
When can we expect to see a new version with this available in NPM?

**Comment by JustinBeckwith** [comment]
I'd like to land the two active PRs, then we will ship a build 😃
