### ISSUE TITLE
JWT client getRequestMetadata should return value

### ISSUE THREAD

**Issue by NicholasHely** [google/google-auth-library-nodejs#36]
Just spent a short while debugging.

```javascript
JWT.prototype.getRequestMetadata = function(opt_uri, cb_with_metadata) {
  if (this.createScopedRequired() && opt_uri) {
    // no scopes have been set, but a uri has been provided.  Use JWTAccess credentials.
    var alt = new JWTAccess(this.email, this.key);
    alt.getRequestMetadata(opt_uri, cb_with_metadata);
  } else {
    JWT.super_.prototype.getRequestMetadata.call(
        this, opt_uri, cb_with_metadata);
  }
};
```

The oauth2client ```getRequestMetaData``` returns a value. And if you look at ```OAuth2Client.prototype.request``` it will return whatever ```getRequestMetadata``` returns. JWT doesn't bubble up the return.

Not returning the value causes issues in https://github.com/google/google-api-nodejs-client/blob/master/lib/apirequest.js where it'll fall over when it tries to pipe the request.

Possible fix, just return the values returned.

```javascript
JWT.prototype.getRequestMetadata = function(opt_uri, cb_with_metadata) {
  if (this.createScopedRequired() && opt_uri) {
    // no scopes have been set, but a uri has been provided.  Use JWTAccess credentials.
    var alt = new JWTAccess(this.email, this.key);
    return alt.getRequestMetadata(opt_uri, cb_with_metadata);
  } else {
    return JWT.super_.prototype.getRequestMetadata.call(
        this, opt_uri, cb_with_metadata);
  }
};
```
Brains not functioning 100%, so if anything didn't make sense, let me know

**Comment by ronkorving** [comment]
I have this problem too. Would be nice to see this fix land.

**Comment by ronkorving** [comment]
Thanks! :)
