### ISSUE TITLE
should increase the example of sending post request

### ISSUE THREAD

**Issue by jianhuafan** [google/google-auth-library-nodejs#360]
I am using this library to use rest api in google cloud ml engine api, and all the examples is client.request({url}) which is get request, how can I pass an object and POST to some google cloud api??

**Comment by JustinBeckwith** [comment]
Greetings!  And thanks for reporting the issue.  If you want to do a post, you mostly follow the docs for [axios](https://github.com/axios/axios), which is what we use under the hood.  For example:

```js
const res = await client.request({
  url: '/some/path',
  method: 'post',
  data: {
    some: 'property',
    another: 15
  }
});
```

That having been said - if you're looking to use Cloud ML Engine, I would really suggest using the `[googleapis](https://github.com/google/google-api-nodejs-client/)` npm module :)

Hope this helps!
