### ISSUE TITLE
IAM sign method

### ISSUE THREAD

**Issue by hiranya911** [google/google-auth-library-nodejs#363]
Can somebody point me to the API reference or the implementation of the sign() method used here: https://github.com/googleapis/nodejs-storage/pull/91

I've gone through google-auth-library, @google-cloud/storage and @google-cloud/common but cannot seem to find that method anywhere. What am I missing?

**Comment by JustinBeckwith** [comment]
Greetings!  The method you're looking for is actually in the `google-auto-auth` library :) 
https://github.com/stephenplusplus/google-auto-auth/blob/master/index.js#L303

FWIW, there's an early PR to pull this forward in #375 

Hope this helps!

**Comment by JustinBeckwith** [comment]
This shipped in 1.6 🎉
