### ISSUE TITLE
ETA for 2.0 release?

### ISSUE THREAD

**Issue by vaskevich** [google/google-auth-library-nodejs#365]
My apologies if this is mentioned somewhere already, but I'm just wondering if there's a planned release date for 2.0 - we're in particular looking to have a release with #307 included. Thanks!

**Comment by JustinBeckwith** [comment]
Hey there!  I think we're going to cherry-pick this one forward and make it a semver minor. I submitted #373, and we'll cut a release after that lands.

**Comment by anthonydelgado** [comment]
💪

**Comment by JustinBeckwith** [comment]
This shipped in 1.6 🎉
