### ISSUE TITLE
Fails `npx tsx` when imported into project: "no exported member 'IncomingHttpHeaders'"

### ISSUE THREAD

**Issue by ChrisOgden** [google/google-auth-library-nodejs#369]
I am utilizing this library for a project that does type checks during a build process via `npx tsc`. When running this test on my project, the test fails because of problems with http not having an exported member of IncomingHttpHeaders. 

![image](https://user-images.githubusercontent.com/13042897/40745323-28932eca-6425-11e8-850d-1c8558e0265c.png)

**Comment by ChrisOgden** [comment]
Files attached. Everything was working until updating to newer versions of google-auth-library and googleapis library from the following:
"google-auth-library": "^0.11.0"
"googleapis": "^22.2.0"

I realize there are large version jumps but the project is getting a review to make sure required packages are up to date.

[tsconfig.json.txt](https://github.com/google/google-auth-library-nodejs/files/2056315/tsconfig.json.txt)
[package.json.txt](https://github.com/google/google-auth-library-nodejs/files/2056328/package.json.txt)

**Comment by JustinBeckwith** [comment]
I am guessing this will fix it:

`npm install --save-dev @types/node`

Can you give that a try and let me know if it works?

**Comment by JustinBeckwith** [comment]
If this is still an issue, feel free to re-open!

**Comment by ChrisOgden** [comment]
No that seems to have resolved it, thank you. Not sure why that was missed. I was in the process of testing it when you commented back.
