### ISSUE TITLE
Error code no longer passed through in response

### ISSUE THREAD

**Issue by bradvogel** [google/google-auth-library-nodejs#37]
[This is cross-posted from https://github.com/google/google-api-nodejs-client/issues/424. I'm not sure what project it should be in.]

I'm using v2.0.3 of this library in the following way:

```
      client.users.drafts.update({
        userId: 'me',
        id: gmailDraftId,
        resource: {
          message: {
            raw: require('base64-url').encode(job.data.emailDraft)
          }
        }
      }, function(err, res, req) {
          // Detect 404 errors
         if (err.code === 404) console.log('does not exist');
      }));
```

In v1.x of this library, `err.code` was populated and correctly set to `404` when the draft didn't exist. However, since I upgraded to 2.x, `err.code` is now undefined. However, the response from the api hasn't changed; `req.body` is still: ` { error: { errors: [Object], code: 404, message: 'Not Found' } } }`.

Did something break in 2.x causing the error code to not get passed through from the response?

**Comment by bradvogel** [comment]
Bump on this @tbetbetbe :)

**Comment by fiznool** [comment]
I have this problem too. The issue is that the response returned from the API server takes the format:

``` js
{ 
  error: { 
    errors: [{ 
      domain: 'global',
      reason: 'authError',
      message: 'Invalid Credentials',
      locationType: 'header',
      location: 'Authorization'
    }], 
    code: 401, 
    message: 'Invalid Credentials'
  }
}
```

but the [error handler](https://github.com/google/google-auth-library-nodejs/blob/ce7f97409908856e2386a650e2fa4de6b2a8211a/lib/transporters.js#L82) is expecting the `code` property to be present inside each item in the `errors` array.

I've fixed this with #38 and updated the test spec to correctly mock the API response.

**Comment by fiznool** [comment]
@tbetbetbe thanks for the super quick merge. Will this be in npm release 0.9.6?

**Comment by tbetbetbe** [comment]
Yes, I aim to get that done this week.

On 18 May 2015 at 07:55, Tom Spencer <notifications@github.com> wrote:

> @tbetbetbe <https://github.com/tbetbetbe> thanks for the super quick
> merge. Will this be in npm release 0.9.6?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-auth-library-nodejs/issues/37#issuecomment-103085843>
> .
>



-- 
This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else (it may
contain confidential or privileged information), please erase all copies of
it, including all attachments, and please let the sender know it went to
the wrong person. Thanks.

**Comment by ryanseys** [comment]
Cool, once the new release it out assuming its 0.9.x, google/google-api-nodejs-client should install this library on fresh installs, eliminating the issue.
