### ISSUE TITLE
OAuth exchange giving invalid_grant and Bad request

### ISSUE THREAD

**Issue by Fleker** [google/google-auth-library-nodejs#379]
I added [a question on StackOverflow](https://stackoverflow.com/questions/50709360/oauth-exchange-giving-invalid-grant-and-bad-request) but I'd also like to bring it up here since it may be an issue with the library as it works fine with curl.

===

I'm running into some weird behavior when trying to use OAuth for a local Node.js script. My goal for right now is to obtain a refresh token from the user when they authorize my project.

I'm trying to rely as much as I can on Google's libraries but am still having issues with it.

When I try to run the setup, I correctly get the OAuth page and create an authorization token:

```js
    const { google } = require('googleapis');

    const oauth2Client = new google.auth.OAuth2(
        clientId,
        clientSecret,
        'urn:ietf:wg:oauth:2.0:oob'
    );
    const scopes = [
        'https://www.googleapis.com/auth/calendar'
    ];
```

I provide the URL to the user in the console:

```js
    const url = oauth2Client.generateAuthUrl({
        // 'online' (default) or 'offline' (gets refresh_token)
        access_type: 'offline',

        // If you only need one scope you can pass it as a string
        scope: scopes
    });

    console.log(url);
```

Then I open the URL and generate the token. I prompt the user to provide this value:

```js
    stdio.question('Authorization code', (err, code) => {
        // Use this code to obtain a refresh token
        console.log("CODE", code);
        oauth2Client.getToken(code, (err, tokens) => {
            console.log(err, tokens);
        });
    });
```

When I get to this point, I run into an error:

    error: 'invalid_grant', error_description: 'Bad Request'

And it's not clear where this is going wrong.

If I take the same auth token and use cURL, it actually works as expected, so it's not a configuration error as far as I can tell.

    curl -s -X POST -d 'code='$CODE'&client_id='$CLIENT_ID'&client_secret='$CLIENT_SECRET'&redirect_uri=urn:ietf:wg:oauth:2.0:oob&grant_type=authorization_code' https://www.googleapis.com/oauth2/v4/token

```js
    {
      "access_token": "ACCESS",
      "token_type": "Bearer",
      "expires_in": 3600,
      "refresh_token": "REFRESH"
    }
```

What's even more interesting is that if I run through the flow and get the error, trying to run the cURL command will return an error that indicates the request was accepted to some degree:

```js
    {
      "error": "invalid_grant",
      "error_description": "Code was already redeemed."
    }
```

What is happening in this OAuth library that is causing the invalid grant issue that is not happening with cURL, and what can I do to correct the Node.js code?

**Comment by JustinBeckwith** [comment]
A few things I've found in researching this so far:
- You need to create an OAuth2 credential for an *installed* application for `urn:ietf:wg:oauth:2.0:oob` to work as a redirect URI
- I can reproduce the issue

**Comment by JustinBeckwith** [comment]
Ok so I figured this out :) The `stdio` npm module is converting the code you're pasting to all lower case.  The code is of course case sensitive, which means 🤷‍♂️   I was able to reproduce your bug and noticed the lower casing of the code, and made sure this works as expected when using the std library.

```js
const {OAuth2Client} = require('google-auth-library');
const readline = require('readline');
const keys = require('./keys');

const clientId = keys.installed.client_id;
const clientSecret = keys.installed.client_secret;

const oauth2Client = new OAuth2Client(
  clientId,
  clientSecret,
  'urn:ietf:wg:oauth:2.0:oob'
);

const scopes = [
  'https://www.googleapis.com/auth/calendar'
];

const url = oauth2Client.generateAuthUrl({
  // 'online' (default) or 'offline' (gets refresh_token)
  access_type: 'offline',

  // If you only need one scope you can pass it as a string
  scope: scopes
});

console.log(url);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('Authorization code: ', (code) => {
  // Use this code to obtain a refresh token
  console.log("CODE", code);
  oauth2Client.getToken(code, (err, tokens) => {
    console.log(err, tokens);
    rl.close();
  });
});
```

Hope this helps!

**Comment by Fleker** [comment]
Thank you. I was really troubled by this issue and it does appear to be a longstanding issue in that library. I really appreciate you looking into this for me.

**Comment by mrdulin** [comment]
same issue. 

```bash
error: 'invalid_grant', error_description: 'Bad Request'
```
What's going on?

**Comment by SpartanByte** [comment]
I am receiving the same issue using OAuth2 and simply hitting the url with parameters in Postman
`https://api.pinterest.com/v1/oauth/token?grant_type=authorization_code&client_id='client_id'&client_secret='client_secret'&code='returned_token`
where 'client_id' = actual client_id, 'client_secret' = actual client secret and 'returned_token' = token ("code") returned from getting the authorization call to connect app to pinterest

**Comment by Niravpatel129** [comment]
> where 'client_id' = actual client_id, 'client_secret' = actual client secret and 'returned_token' = token ("code") returned from getting the authorization call to connect app to pinterest

same issue when using postman.
