### ISSUE TITLE
GoogleAuth#getProjectId vs. GoogleAuth#getDefaultProjectId

### ISSUE THREAD

**Issue by ofrobots** [google/google-auth-library-nodejs#389]
These are synonyms of each other, but given then name, these should NOT be.

I would intuit that `getDefaultProjectId` always gives the default project Id as per the environment (GCLOUD_PROJECT, GOOGLE_APPLICATION_CREDENTIALS, fetch from metadata service, etc.) and never the configured one. As named, it is intuitively incorrect for it to return the configured projectId.

I don't see a reason why both of these names should exist, unless we want to support both behaviours.

IMO, `getDefaultProjectId` should be dropped. If we want to keep both names, they should do what their names say they do.

**Comment by ofrobots** [comment]
IOW, this test (https://github.com/google/google-auth-library-nodejs/pull/388) makes sense to pass for `getProjectId`, but not for `getDefaultProjectId`.

**Comment by ofrobots** [comment]
@JustinBeckwith it seems like the behaviour of `getDefaultProjectId` was changed in https://github.com/google/google-auth-library-nodejs/pull/281. Before that it used to do what the name implied.

**Comment by JustinBeckwith** [comment]
Yikes.  You're totally right.  In the spirit of semver, what do you think makes the most sense here?  I broke the behavior in a semver minor change.  Would it be semver minor to change it back?  Or does it make more sense to do a major rev?

**Comment by JustinBeckwith** [comment]
Taking a closer look here - I don't think having a method that just gets the default projectId is actually valuable.  Happy to hear scenarios if you think it is 🤷‍♂️ 

Given that, I prefer just deleting the `getDefaultProjectId` method all together.  Thoughts?

**Comment by ofrobots** [comment]
👍 on removing `getDefaultProjectId` as suggested in OP.

**Comment by JustinBeckwith** [comment]
Fixed in #402
