### ISSUE TITLE
TS issue

### ISSUE THREAD

**Issue by node-ist** [google/google-auth-library-nodejs#393]
Hello,i added this library and when i try to start tsc i have this error, can some one help me?
![screenshot_20180627_095741](https://user-images.githubusercontent.com/20520686/41957934-30101690-79f1-11e8-9e59-043400598a78.png)
![screenshot_20180627_100253](https://user-images.githubusercontent.com/20520686/41957972-4e56ff56-79f1-11e8-93bd-821778e9b7f5.png)

**Comment by JustinBeckwith** [comment]
Please try to `npm install --save-dev @types/node` and recompile :)

**Comment by node-ist** [comment]
still the same :(
![image](https://user-images.githubusercontent.com/20520686/41958513-f2c521ac-79f2-11e8-9d6f-e2058e5915ec.png)

**Comment by node-ist** [comment]
http doesn't have interface IncomingHttpHeaders, if i change it in to RequestOptions it works

**Comment by node-ist** [comment]
![image](https://user-images.githubusercontent.com/20520686/41959572-066055d0-79f6-11e8-9e92-f9ae8e376907.png)
It's all interfaces of http

**Comment by node-ist** [comment]
But this changes i can do only in node_modules, so can you fix it?

**Comment by JustinBeckwith** [comment]
I'm struggling to reproduce this :(  Would it be possible to create a github repo with a small example?  This is what's working for me:

```
node.js: 10.5.0
npm: 6.1.0
 ```
### package.json
```js
{
  "devDependencies": {
    "typescript": "^2.9.2"
  },
  "dependencies": {
    "google-auth-library": "^1.6.1"
  }
}
```

### tsconfig.json
```js
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "include": ["*.ts"]
}
```

### main.ts
```js
import {auth} from 'google-auth-library';

async function main() {
  const res = await auth.getRequestHeaders();
  console.log(res);
}

main().catch(console.error);
```

Then go run:

```
$ npx tsc -p .
$ node main.js
```

Can you give these steps a try?
