### ISSUE TITLE
[Drive] TypeError: authClient.request is not a function

### ISSUE THREAD

**Issue by jurbina1** [google/google-auth-library-nodejs#426]
I am currently following this tutorial: https://developers.google.com/drive/api/v3/quickstart/nodejs

I didn't change the code and it gives me the following error:

(node:46228) UnhandledPromiseRejectionWarning: TypeError: authClient.request is not a function
    at Object.createAPIRequest (/Users/.../node_modules/googleapis/build/src/lib/apirequest.js:193:20)
    at Object.list (/Users/.../node_modules/googleapis/build/src/apis/drive/v3.js:469:33)
    at listFiles (/Users/.../Desktop/sample1.js:72:15)
    at oAuth2Client.getToken (/Users/.../Desktop/sample1.js:54:23)
    at /Users/.../node_modules/google-auth-library/build/src/auth/oauth2client.js:158:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:46228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:46228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't really know what's the problem and I tried the tutorial in python (to see if I had the same problem) and it works, but I need to be able to do this in nodejs.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share a few things with me?
- The version of node.js you're running
- Your `package.json`
- The exact code you're trying to run :)

Thanks!

**Comment by jurbina1** [comment]
NodeJS version: 10.4.1

I am currently not using a `package.json` since it didn't say anything in the Quickstart Guide.

**Code:**
const fs = require('fs');
const readline = require('readline');
const {google} = require('googleapis');

// If modifying these scopes, delete credentials.json.
const SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly'];
const TOKEN_PATH = 'token.json';

// Load client secrets from a local file.
fs.readFile('credentials.json', (err, content) => {
  if (err) return console.log('Error loading client secret file:', err);
  // Authorize a client with credentials, then call the Google Drive API.
  authorize(JSON.parse(content), listFiles);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  const {client_secret, client_id, redirect_uris} = credentials.installed;
  const oAuth2Client = new google.auth.OAuth2(
      client_id, client_secret, redirect_uris[0]);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, (err, token) => {
    if (err) return getAccessToken(oAuth2Client, callback);
    oAuth2Client.setCredentials(JSON.parse(token));
    callback(oAuth2Client);
  });
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 * @param {google.auth.OAuth2} oAuth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback for the authorized client.
 */
function getAccessToken(oAuth2Client, callback) {
  const authUrl = oAuth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
  });
  console.log('Authorize this app by visiting this url:', authUrl);
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  rl.question('Enter the code from that page here: ', (code) => {
    rl.close();
    const {tokens} = oAuth2Client.getToken(code)
    oAuth2Client.setCredentials(tokens);
    fs.writeFile(TOKEN_PATH, JSON.stringify(tokens), (err) => {
        if (err) console.error(err);
        console.log('Token stored to', TOKEN_PATH);
    });
    callback(oAuth2Client);
    /**oAuth2Client.getToken(code, (err, token) => {
      if (err) return callback(err);
      oAuth2Client.setCredentials(token);
      // Store the token to disk for later program executions
      fs.writeFile(TOKEN_PATH, JSON.stringify(token), (err) => {
        if (err) console.error(err);
        console.log('Token stored to', TOKEN_PATH);
      });
      callback(oAuth2Client);
    });**/
  });
}

/**
 * Lists the names and IDs of up to 10 files.
 * @param {google.auth.OAuth2} auth An authorized OAuth2 client.
 */
function listFiles(auth) {
  const drive = google.drive({version: 'v3', auth});
  drive.files.list({
    pageSize: 10,
    fields: 'nextPageToken, files(id, name)',
  }, (err, res) => {
    if (err) return console.log('The API returned an error: ' + err);
    const files = res.data.files;
    if (files.length) {
      console.log('Files:');
      files.map((file) => {
        console.log(`${file.name} (${file.id})`);
      });
    } else {
      console.log('No files found.');
    }
  });
}

**Comment by JustinBeckwith** [comment]
Just to make things easier to debug - can you run:

```
npm init -y
npm install googleapis
```

**Comment by jurbina1** [comment]
Okay. This is `package.json`

```{
  "name": "Desktop",
  "version": "1.0.0",
  "description": "",
  "main": "sample1.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "googleapis": "^32.0.0"
  }
}
```

**Comment by jcmoscon** [comment]
I'm having the same problem. Any idea why is this happening?

**Comment by danepowell** [comment]
Same problem here trying to use auth.getClient(). The error seems to indicate an authentication problem, albeit not very well. No clue what exactly caused it though. I switched to JWT auth in order to work around it.

**Comment by JustinBeckwith** [comment]
Greetings folks!  I need a few more details here.  This seems to work on the latest version for me.  Can you please verify that:
- You are using the most recent version of the `googleapis` npm module
- You are *not* directly installing this module if you're using `googleapis`

I am going to close this out for now.  If you are still having problems, please open a new issue with a copy of your package.json :)
