### ISSUE TITLE
this libraray is useful to send emails ?

### ISSUE THREAD

**Issue by webmobiles** [google/google-auth-library-nodejs#427]
I'm lost with google apis, it looks not easy to understand
is this libraray useful to send emails?
thanks

**Comment by JustinBeckwith** [comment]
Greetings!  You're looking for the `googleapis` npm module :)  I even wrote a sample!  
https://github.com/google/google-api-nodejs-client/blob/master/samples/gmail/send.js

If you have any issues, feel free to open a bug on that repo.

**Comment by webmobiles** [comment]
thanks ! now i understand better, but i'm having a problem sending the email, the issues that i've added is on:
https://github.com/google/google-api-nodejs-client/issues/1250

please take a look
thanks
