### ISSUE TITLE
TypeError: Not a Buffer

### ISSUE THREAD

**Issue by brunolazzaro** [google/google-auth-library-nodejs#46]
When using the `verifyIdToken` to verify a really old token (So far I only encoutered with these kind of tokens), instead of getting an expired error the app throws this error.

I've digged a bit and found that the main issues resides within the line 495 in `oauth2client.js`:

```
var pem = certs[envelope.kid];
```

That resolves to undefined sometimes. `envelope.kid` holds a value, but not one that matches the certs generated by the `getFederatedSignonCerts` function in `oauth2client.js`, thus causing the `pemVerifier.verify` throw.

**Comment by crspybits** [comment]
In your case, how old was a "really old token"? I'm getting this error with an id token that was about 2 days old. Guess I'm not really sure how long they are supposed to last.

**Comment by brunolazzaro** [comment]
I don't recall right now, but I think that if you try to use a token that it's a day old you should get this error.

**Comment by crspybits** [comment]
In the same verifyIdToken call, I'm now getting errors like "Token used too late, 1449031980.079 > 1449029024". I'm not sure if there is some variability in what gets returned from Google's servers, or if some change occurred to those servers.

I think these numbers are referring to the "exp" field of the IdToken, which has the definition:
"The time the ID token expires, represented in Unix time (integer seconds)."
(https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo)

I'll have to see if I can get the IdToken exp field immediately after obtaining the IdToken and convert the Unix time to a h/m/s time.

**Comment by brunolazzaro** [comment]
That is the expected behavior. If a token has expired, then you'll recieve that error. The issue that I'm describing is when instead of getting the correct error (Token userd too late) the `pemVerify.verify` call throws an error.

**Comment by brunolazzaro** [comment]
That error is to be expected if the token actually expired (You should check the `expires_in` field if there is any in your response). The issue I'm describing is that instead of getting the correct error (Token used too late) the `perVerify.verify` call throws an error due to the issue explained above.

If you're getting "Token used too late" you should refresh your access tokens.
