### ISSUE TITLE
Error 'The incoming JSON object does not contain a client_email field' on JSON keys

### ISSUE THREAD

**Issue by ofrobots** [google/google-auth-library-nodejs#47]
Lately the Google Developer console has been giving me JSON service account keys with empty `client_email` and `client_id` fields. These are being generated at https://github.com/google/google-auth-library-nodejs/blob/71511d08a05253ede89930342ccdf4c48f93bead/lib/auth/jwtaccess.js#L101

Either there is a bug in this library (as in having an expectation that `client_email` must be present), or there is a bug in the developer console (as in generating a key without the required `client_email` property), but I will start by opening the bug here.

Here's an excerpt from a key I got today. I have verified that others are also getting keys with empty `client_email`.
```
  ..... ----END PRIVATE KEY-----\n",
  "client_email": "",
  "client_id": "",
  "type": "service_account"
}
```

**Comment by tbetbetbe** [comment]
@anthmgoogle PTAL

**Comment by anthmgoogle** [comment]
This is definitely a probelm with the developers console, not the client library.

There was an issue that was affecting @google.com users only that the first key was empty. Is it not expected if this is affecting users more broadly. In that case a work around was to generate a second key for the service account.

**Comment by ofrobots** [comment]
Okay. I have generated several keys yesterday (some in quick succession) and today and all of them are lacking the `client_email` section.

**Comment by anthmgoogle** [comment]
I just tried it and keys are coming back with valid emails. We need to escalate this with the console to understand the boundaries of this.

**Comment by anthmgoogle** [comment]
Update. I just verified that this seems to match a known issue that should only affect Google employees because of a pre-release version of the console. Creating new service accounts result in a blank email. Subsequently related keys are valid and should work around the issue.

**Comment by murgatroid99** [comment]
OK, this appears to not be a problem with this library, and also fixed.
