### ISSUE TITLE
JwtAccess Credentials Feature

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-nodejs#50]
Tracking completion of implementation of JwtAccess Credentials for service accounts for NodeJS. This is a service account that passes a JWT directly as an a bearer token instead of exchanging for an access token.

For reference, the Java implementation:
https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java

**Comment by tbetbetbe** [comment]
This was already added in #29

Please re-open the issue if you are referring to a different feature
