### ISSUE TITLE
Jwt Access Credentials should cache JWTs

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-nodejs#52]
The JWT Access Credentials should temporarily cache JWTs. Suggested algorithm:
- Hash JWTs using Audience as key.
- Also store the timestamp of last use with each JWT.
- On access clear any JWT unused for more than 1 hour.

**Comment by JustinBeckwith** [comment]
Out of curiosity, @jonparrott / @lukesneeringer is this something you do in the python client?

**Comment by jonparrott** [comment]
Yes, see https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/jwt.py#L497

**Comment by JustinBeckwith** [comment]
Interesting!  Out of curiosity - what are the use cases for the configurable cache size and expiration window?

**Comment by jonparrott** [comment]
The cache size and expiration window are not configurable for Python. It's rare for an application to talk to any memory-significant number audiences with the same set of credentials, and the expiration time is just the same as the JWT expiration time.

**Comment by JustinBeckwith** [comment]
Addressed in #254, will go out in the upcoming 1.1.0 release.
