### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stephenplusplus** [google/google-auth-library-nodejs#53]
Hello, I just wanted to check if any documentation has been planned for this module? Something like [this](https://github.com/sindresorhus/got#api) is a generally accepted format for docs. Maybe for this module, they can be grouped by auth types?

---
## Default Credentials

This library provides an implementation of application default credentials for Node.js.

...
### Example

``` js
var GoogleAuth = require('google-auth-library');
// ...
```
##### callback.err
- Type: `Error`

An error occurred while trying to find the default credentials.
##### callback.authClient
- Type: `Object`
###### createScopeRequired
- Type: `Function`

If defined, scopes are required.

This is just a skeleton, it can of course be modified to your liking.

Thanks!

**Comment by JustinBeckwith** [comment]
Closing this in favor of #206
