### ISSUE TITLE
Add convenience methods for common use cases

### ISSUE THREAD

**Issue by stephenplusplus** [google/google-auth-library-nodejs#54]
Hello again!

I was wondering if it would be possible to design some convenience wrappers around common uses for this library?

I can't appreciate all the nuances and complexities this library has to support, so I can't comment on all of the use cases that can be simplified. But as an example, I made google-auto-auth to make authing with application default, JSON/p12 keyfile, and credentials JS objects easier: https://github.com/stephenplusplus/google-auto-auth/blob/0bea71c76c46158a4a4911b3f16af35f7a16ae9d/index.js#L81-L92

I'm still not entirely sure I'm using this library's API the right way (#53), but a developer using google-auto-auth is surely going to have an easier time getting started.

Thanks!

**Comment by ofrobots** [comment]
@stephenplusplus do you still care about this?

**Comment by stephenplusplus** [comment]
This is what started all these issues: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/832

Ideally, this library would be easier to use and better documented so we could replace and deprecate google-auto-auth.

**Comment by ofrobots** [comment]
Hmm.. I quite like `google-auto-auth` – it is nice and easy to use. Do we still want to deprecate it?

/cc @JustinBeckwith

**Comment by stephenplusplus** [comment]
I don't mind either way :)
