### ISSUE TITLE
gcloud doc support for google-auth-library-nodejs

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-nodejs#56]
google-auth-library-nodejs is an important dependency for gcloud-node. Enable doc publishing so that documentation appears along with the rest of the gcloud doc system.

**Comment by JustinBeckwith** [comment]
We're tracking the reference docs over in #206.  As far as integrating with our gcloud docs - I'm not sure if that's going to be possible given the fact that we're not using jsdoc.  

@jmdobry what do you think?  I'm using typedoc, and we have a preview here:
http://google.github.io/google-auth-library-nodejs/

**Comment by JustinBeckwith** [comment]
FYI - reference docs just landed in master.

**Comment by JustinBeckwith** [comment]
Given the fact that we're using TypeScript here, and we're using TypeDoc for doc generation - it's unlikely that we're going to get to integrating this with the existing docset anytime soon.  I'm going to go ahead and close this out for now.  If others think this should be re-opened - let me know!
