### ISSUE TITLE
A proxy setting in getToken

### ISSUE THREAD

**Issue by jojonki** [google/google-auth-library-nodejs#65]
I faced a trouble of setting proxy during getting token. When this library tries to get token, it looks it doesn't consider proxy setting. My code works if I set a proxy as a request property directly.
https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/oauth2client.js#L143

Or are there any ways to setting proxy even if trying to getting tokens?

**Comment by runk** [comment]
Stuck at the same issue.

You can set `HTTP_PROXY` and `HTTPS_PROXY` environment vars to corresponding value. Those vars are recognized by `request` module which `google-auth-library-nodejs` uses internally

**Comment by JustinBeckwith** [comment]
Turns out this works out of the box via the `HTTP_PROXY` and `HTTPS_PROXY` env vars :)  Adding  docs around that in #221.
