### ISSUE TITLE
automatic token refresh is not happening in getrequestmetadata

### ISSUE THREAD

**Issue by ssuda** [google/google-auth-library-nodejs#67]
incase of 401 or 403, automatic token refresh used happen before.
But it is not happening now.  Is it removed or bug?

**Comment by L422Y** [comment]
I still seem to be having this issue, my application will work fine and then eventually only get `{ error: 'unauthorized_client' }` responses from the server until I manually go through getting new keys.

**Comment by JustinBeckwith** [comment]
Greetings!  We have a fair bit of code and tests in place to make sure this works.  We've also made a few recent changes (like #242) that should make it even better.  If you're still having issues here, providing a code snippet to reproduce the issue would be *super* helpful. 

Thanks!
