### ISSUE TITLE
generateAuthUrl doesn't pass state token

### ISSUE THREAD

**Issue by rodrigogoncalves** [google/google-auth-library-nodejs#71]
Should the `generateAuthUrl` method from OAuth2Client accept a `state` param in order to generate an auth url that provides anti-forgery unique session token validation?

The implementation flow suggested by Google ([link](https://developers.google.com/identity/protocols/OpenIDConnect)) uses an auth url with the state param.

**Comment by murgatroid99** [comment]
As far as I can tell, that is already supported. If you call `generateAuthUrl({state: state})`, then that should be propagated to the output. The same is true of any other parameter that can go into the auth library.

**Comment by rodrigogoncalves** [comment]
It is true, that parameter is sent back in the response. It was just undocumented.

**Comment by rodrigogoncalves** [comment]
Please @JustinBeckwith, do not assign this to me.
