### ISSUE TITLE
Very pathetic documentation!!

### ISSUE THREAD

**Issue by nidhind** [google/google-auth-library-nodejs#72]
I wanted you to note this point. Thats why I opened this as an issue. A good detailed document will never do any bad. Its really hard to find how to use this. Please update this doc so that users with all levels of experience like novice to professionals can seamlessly use this.

**Comment by stephenplusplus** [comment]
Related: https://github.com/google/google-auth-library-nodejs/issues/53

**Comment by stephenplusplus** [comment]
@nidhind in the meantime, you might like [google-auto-auth](https://github.com/stephenplusplus/google-auto-auth). This library (google-auth-library-nodejs) intends to match that API (google-auto-auth's) more closely in the future, but for getting started quickly, it might be helpful for now.

**Comment by tbetbetbe** [comment]
We've updated the main README.md in release 0.9.8.  Please take a look at the changes in #85, and let me know what you think.

**Comment by nidhind** [comment]
I guess little more details needs to be added.  A _working clone-able example _like this one: https://github.com/ParsePlatform/parse-server-example will be very nice. Thanks for your effort.
