### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by jimkang** [google/google-auth-library-nodejs#87]
I want to use this in the browser via Browserify, but it looks like it depends on process.env. Is there another way to use Application Default Credentials in the browser? I've searched and can't seem to find anything.

**Comment by JustinBeckwith** [comment]
Greetings!  Something like Application Default Credentials in the browser is problematic.  Generally ADC is focused on service<->service communication, and requires the use of private keys.  

If you're doing something in the browser, generally you want to either:
1. Use an OAuth2 workflow to perform actions on behalf of the user, or
2. Send information to your backend, which then uses ADC to communicate with Google APIs

Based on which of these you want to do - I'll have a difference answer on how to do it :)

**Comment by JustinBeckwith** [comment]
If this is still an issue, let us know!  I would be happen to take another look.
