### ISSUE TITLE
Dependency `request` ~2.60.0 is insecure

### ISSUE THREAD

**Issue by ktrain** [google/google-auth-library-nodejs#99]
`request` <2.68.0 >2.2.5 has a vulnerability: https://snyk.io/vuln/npm:request:20160119

I see that it's updated to ~2.74.0 in `master`. Is v0.9.9 going to be released soon?

**Comment by murgatroid99** [comment]
v0.9.9 has now been released, which I think resolved this issue.

**Comment by ktrain** [comment]
Awesome, thank you!
<img height="300" src="https://33.media.tumblr.com/2dfc3369827df9b981e111d7fd8fc732/tumblr_mvemcyarmn1rslphyo1_400.gif" />
